# ARENA
SCREEN_WIDTH = 720
SCREEN_HEIGHT = 720
FPS = 60
BACKGROUND_COLOR = (10, 12, 20)
WALL_COLOR = (60, 65, 80)

# BALLS
BALL_RADIUS = 44
BALL_SPEED = 6.0
BALL_HP = 100

# HIT SYSTEM
HIT_COOLDOWN = 0.5

# SWORD BALL
SWORD_ORBIT_RADIUS    = round(BALL_RADIUS * 2.2)   # 48 at r=22
SWORD_LENGTH          = round(BALL_RADIUS * 1.82)  # 40 at r=22
SWORD_WIDTH           = round(BALL_RADIUS * 0.36)  # 8 at r=22
SWORD_ROTATION_SPEED  = 4.0
SWORD_DAMAGE          = 18
SWORD_COLOR           = (180, 210, 255)
SWORD_TIP_COLOR       = (220, 240, 255)
SWORD_GLOW_RADIUS     = round(BALL_RADIUS * 0.18)  # 4 at r=22

# GUN BALL
GUN_FIRE_INTERVAL           = 1.2
GUN_BARREL_LENGTH           = round(BALL_RADIUS * 0.55)  # 12 at r=22
GUN_BARREL_WIDTH            = 6
GUN_BARREL_COLOR            = (255, 180, 60)
GUN_MUZZLE_COLOR            = (255, 240, 100)
GUN_MUZZLE_FLASH_FRAMES     = 3
GUN_MUZZLE_FLASH_RADIUS_STEP = 5
BULLET_SPEED                = 9
BULLET_MAX_DISTANCE         = 900
BULLET_DAMAGE               = 15
BULLET_WIDTH                = 14
BULLET_HEIGHT               = 5
BULLET_COLOR                = (255, 200, 80)
BULLET_TRAIL_LENGTH         = 4
BULLET_TRAIL_RADIUS         = 3
BULLET_TRAIL_MAX_ALPHA      = 80

# TETHER BALL
TETHER_ORBIT_RADIUS    = round(BALL_RADIUS * 2.73)  # 60 at r=22
TETHER_WEIGHT_RADIUS   = round(BALL_RADIUS * 0.45)  # 10 at r=22
TETHER_LAG_FACTOR      = 0.08
TETHER_WHIP_BOOST      = 3.5
TETHER_DAMAGE          = 22
TETHER_ANG_VEL_DECAY   = 0.9
TETHER_CHAIN_COLOR     = (130, 130, 140)
TETHER_CHAIN_DASH      = 6
TETHER_CHAIN_GAP       = 4
TETHER_CHAIN_WIDTH     = 2
TETHER_WEIGHT_COLOR    = (90, 60, 120)
TETHER_TRAIL_LENGTH    = 5
TETHER_TRAIL_RADIUS    = round(BALL_RADIUS * 0.18)  # 4 at r=22
TETHER_TRAIL_MAX_ALPHA = 120

# TRAP LAYER
MINE_DROP_INTERVAL    = 1.8
MINE_RADIUS           = round(BALL_RADIUS * 0.45)   # 10 at r=22
MINE_PROXIMITY_RADIUS = round(BALL_RADIUS * 1.27)   # 28 at r=22
MINE_DAMAGE           = 25
MINE_LIFETIME         = 10.0
MINE_FADE_START       = 7.0
MINE_COLOR            = (30, 80, 30)
MINE_RING_COLOR       = (180, 40, 40)
MINE_RING_ALPHA_BASE  = 80
MINE_RING_ALPHA_AMP   = 50
MINE_PULSE_SPEED      = 4.0
TRAP_TRAIL_LENGTH     = 3
TRAP_TRAIL_ALPHA_MIN  = 15
TRAP_TRAIL_ALPHA_MAX  = 30

# VISUAL
GLOW_LAYERS            = 4
GLOW_LAYER_STEP        = 4
GLOW_ALPHA_START       = 40
OUTLINE_BRIGHT_AMOUNT  = 30
OUTLINE_RADIUS_OFFSET  = 1
OUTLINE_WIDTH          = 2
FLICKER_ALPHA_MIN      = 100
PARTICLE_COUNT_HIT     = 8
PARTICLE_COUNT_MINE    = 12
PARTICLE_COUNT_DEATH   = 28
PARTICLE_LIFETIME      = 0.6
DEATH_PARTICLE_LIFETIME = 1.2
PARTICLE_MAX_COUNT     = 150
PARTICLE_HIT_SPEED_MIN  = 60
PARTICLE_HIT_SPEED_MAX  = 120
PARTICLE_HIT_RADIUS_MIN = 3
PARTICLE_HIT_RADIUS_MAX = 5
PARTICLE_DEATH_SPEED_MIN  = 150
PARTICLE_DEATH_SPEED_MAX  = 300
PARTICLE_DEATH_RADIUS_MIN = 4
PARTICLE_DEATH_RADIUS_MAX = 7
PARTICLE_DEATH_GRAVITY    = 150.0
PARTICLE_MINE_SPEED_MIN  = 100
PARTICLE_MINE_SPEED_MAX  = 200
PARTICLE_MINE_RADIUS_MIN = 3
PARTICLE_MINE_RADIUS_MAX = 6
PARTICLE_COUNT_SPARK   = 3
PARTICLE_SPARK_SPEED_MIN = 150
PARTICLE_SPARK_SPEED_MAX = 250
PARTICLE_SPARK_RADIUS  = 3
PARTICLE_SPARK_LIFETIME = 0.2
MINE_PARTICLE_COLOR    = (220, 80, 30)
MINE_FLASH_START_RADIUS = 5.0
MINE_FLASH_MAX_RADIUS  = 40
MINE_FLASH_FRAMES      = 3
MINE_FLASH_EXPAND_FACTOR = 0.8
SCREEN_SHAKE_FRAMES    = 4
SCREEN_SHAKE_MAGNITUDE = 5
LOW_HP_THRESHOLD       = 25
FLICKER_INTERVAL       = 0.4

# HUD
HUD_BAR_WIDTH           = 280
HUD_BAR_HEIGHT          = 18
HUD_BAR_Y               = 40
HUD_BAR_MARGIN          = 30
HUD_FONT_SIZE           = 22
HUD_LABEL_GAP           = 4
HUD_BAR_BG_COLOR        = (30, 30, 40)
HUD_TEXT_COLOR          = (255, 255, 255)
HUD_BAR_YELLOW          = (220, 180, 0)
HUD_BAR_RED             = (200, 40, 40)
HUD_HP_YELLOW_THRESHOLD = 0.6
HUD_HP_RED_THRESHOLD    = 0.25
