# ARENA
SCREEN_WIDTH = 720
SCREEN_HEIGHT = 1280
FPS = 60
BACKGROUND_COLOR = (10, 12, 20)
WALL_COLOR = (60, 65, 80)

# BALLS
BALL_RADIUS = 22
BALL_SPEED = 4.5
BALL_HP = 100

# HIT SYSTEM
HIT_COOLDOWN = 0.5

# SWORD BALL
SWORD_ORBIT_RADIUS = 48
SWORD_LENGTH = 40
SWORD_WIDTH = 8
SWORD_ROTATION_SPEED = 4.0
SWORD_DAMAGE = 18

# GUN BALL
GUN_FIRE_INTERVAL = 1.2
BULLET_SPEED = 9
BULLET_MAX_DISTANCE = 900
BULLET_DAMAGE = 15
BULLET_WIDTH = 14
BULLET_HEIGHT = 5

# TETHER BALL
TETHER_ORBIT_RADIUS = 60
TETHER_WEIGHT_RADIUS = 10
TETHER_LAG_FACTOR = 0.08
TETHER_WHIP_BOOST = 3.5
TETHER_DAMAGE = 22

# TRAP LAYER
MINE_DROP_INTERVAL = 1.8
MINE_RADIUS = 10
MINE_PROXIMITY_RADIUS = 28
MINE_DAMAGE = 25
MINE_LIFETIME = 10.0
MINE_FADE_START = 7.0

# VISUAL
GLOW_LAYERS = 4
GLOW_ALPHA_START = 40
PARTICLE_COUNT_HIT = 8
PARTICLE_COUNT_MINE = 12
PARTICLE_COUNT_DEATH = 28
PARTICLE_LIFETIME = 0.6
DEATH_PARTICLE_LIFETIME = 1.2
SCREEN_SHAKE_FRAMES = 4
SCREEN_SHAKE_MAGNITUDE = 5
LOW_HP_THRESHOLD = 25
FLICKER_INTERVAL = 0.4

# HUD
HUD_BAR_WIDTH = 280
HUD_BAR_HEIGHT = 18
HUD_BAR_Y = 40
HUD_BAR_MARGIN = 30
HUD_FONT_SIZE = 22
